// These constants represent the RISC-V ELF and the image ID generated by risc0-build.
// The ELF is used for proving and the ID is used for verification.
// use methods::{
//     GUEST_ELF, GUEST_ID
// };

pub const GUEST_ELF: &[u8] = include_bytes!("/Users/christophe/Documents/Work/local-domain/target/riscv-guest/methods/guest/riscv32im-risc0-zkvm-elf/release/guest.bin");
pub const GUEST_PATH: &str = "/Users/christophe/Documents/Work/local-domain/target/riscv-guest/methods/guest/riscv32im-risc0-zkvm-elf/release/guest.bin";
pub const GUEST_ID: [u32; 8] = [2851637215, 2896995163, 2541865285, 1266731898, 374983357, 2762390881, 1603618658, 3212536150];


use risc0_zkvm::{default_prover, ExecutorEnv};

pub fn provetest() -> u32 {
    // Initialize tracing. In order to view logs, run `RUST_LOG=info cargo run`
    // tracing_subscriber::fmt()
    //     .with_env_filter(tracing_subscriber::filter::EnvFilter::from_default_env())
    //     .init();

    // An executor environment describes the configurations for the zkVM
    // including program inputs.
    // A default ExecutorEnv can be created like so:
    // `let env = ExecutorEnv::builder().build().unwrap();`
    // However, this `env` does not have any inputs.
    //
    // To add guest input to the executor environment, use
    // ExecutorEnvBuilder::write().
    // To access this method, you'll need to use ExecutorEnv::builder(), which
    // creates an ExecutorEnvBuilder. When you're done adding input, call
    // ExecutorEnvBuilder::build().

    // For example:
    let input: u32 = 15 * u32::pow(2, 27) + 1;
    let env = ExecutorEnv::builder()
        .write(&input)
        .unwrap()
        .build()
        .unwrap();

    println!("get prover");
    // Obtain the default prover.
    let prover = default_prover();

    println!("provetest");
    // Proof information by proving the specified ELF binary.
    // This struct contains the receipt along with statistics about execution of the guest
    let prove_info = prover
        .prove(env, GUEST_ELF)
        .unwrap();

    println!("receipt");
    // extract the receipt.
    let receipt = prove_info.receipt;

    // TODO: Implement code for retrieving receipt journal here.
    println!("fetch rceipt");
    // For example:
    let output: u32 = receipt.journal.decode().unwrap();

    // // The receipt was verified at the end of proving, but the below code is an
    // // example of how someone else could verify this receipt.
    // let result = receipt
    //     .verify(GUEST_ID)
    //     .unwrap();

    output
}

#[rustler::nif]
fn test() -> u32 {
    println!("Hello, world!");
    provetest()
}
rustler::init!("Elixir.LocalDomain.Host");
